/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as WorkoutIndexRouteImport } from './routes/workout.index'
import { Route as WorkoutExerciseExerciseIdRouteImport } from './routes/workout.exercise.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutExerciseExerciseIdRoute =
  WorkoutExerciseExerciseIdRouteImport.update({
    id: '/workout/exercise/$exerciseId',
    path: '/workout/exercise/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/exercise/$exerciseId': typeof WorkoutExerciseExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workout': typeof WorkoutIndexRoute
  '/workout/exercise/$exerciseId': typeof WorkoutExerciseExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/exercise/$exerciseId': typeof WorkoutExerciseExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/workout/' | '/workout/exercise/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/workout' | '/workout/exercise/$exerciseId'
  id: '__root__' | '/' | '/home' | '/workout/' | '/workout/exercise/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  WorkoutExerciseExerciseIdRoute: typeof WorkoutExerciseExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/exercise/$exerciseId': {
      id: '/workout/exercise/$exerciseId'
      path: '/workout/exercise/$exerciseId'
      fullPath: '/workout/exercise/$exerciseId'
      preLoaderRoute: typeof WorkoutExerciseExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  WorkoutExerciseExerciseIdRoute: WorkoutExerciseExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
