/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as WorkoutIndexRouteImport } from './routes/workout.index'
import { Route as WorkoutActiveRouteImport } from './routes/workout.active'
import { Route as WorkoutSummaryRouteImport } from './routes/workout.summary'
import { Route as WorkoutExerciseExerciseIdRouteImport } from './routes/workout.exercise.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutActiveRoute = WorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummaryRoute = WorkoutSummaryRouteImport.update({
  id: '/workout/summary',
  path: '/workout/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutExerciseExerciseIdRoute =
  WorkoutExerciseExerciseIdRouteImport.update({
    id: '/workout/exercise/$exerciseId',
    path: '/workout/exercise/$exerciseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/progress': typeof ProgressRoute
  '/recovery': typeof RecoveryRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/exercise/$exerciseId': typeof WorkoutExerciseExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/progress': typeof ProgressRoute
  '/recovery': typeof RecoveryRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/workout': typeof WorkoutIndexRoute
  '/workout/exercise/$exerciseId': typeof WorkoutExerciseExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/progress': typeof ProgressRoute
  '/recovery': typeof RecoveryRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/summary': typeof WorkoutSummaryRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/exercise/$exerciseId': typeof WorkoutExerciseExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/home'
    | '/nutrition'
    | '/progress'
    | '/recovery'
    | '/workout/active'
    | '/workout/summary'
    | '/workout/'
    | '/workout/exercise/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/home'
    | '/nutrition'
    | '/progress'
    | '/recovery'
    | '/workout/active'
    | '/workout/summary'
    | '/workout'
    | '/workout/exercise/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/home'
    | '/nutrition'
    | '/progress'
    | '/recovery'
    | '/workout/active'
    | '/workout/summary'
    | '/workout/'
    | '/workout/exercise/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  HomeRoute: typeof HomeRoute
  NutritionRoute: typeof NutritionRoute
  ProgressRoute: typeof ProgressRoute
  RecoveryRoute: typeof RecoveryRoute
  WorkoutActiveRoute: typeof WorkoutActiveRoute
  WorkoutSummaryRoute: typeof WorkoutSummaryRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  WorkoutExerciseExerciseIdRoute: typeof WorkoutExerciseExerciseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/active': {
      id: '/workout/active'
      path: '/workout/active'
      fullPath: '/workout/active'
      preLoaderRoute: typeof WorkoutActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/summary': {
      id: '/workout/summary'
      path: '/workout/summary'
      fullPath: '/workout/summary'
      preLoaderRoute: typeof WorkoutSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/exercise/$exerciseId': {
      id: '/workout/exercise/$exerciseId'
      path: '/workout/exercise/$exerciseId'
      fullPath: '/workout/exercise/$exerciseId'
      preLoaderRoute: typeof WorkoutExerciseExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  HomeRoute: HomeRoute,
  NutritionRoute: NutritionRoute,
  ProgressRoute: ProgressRoute,
  RecoveryRoute: RecoveryRoute,
  WorkoutActiveRoute: WorkoutActiveRoute,
  WorkoutSummaryRoute: WorkoutSummaryRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  WorkoutExerciseExerciseIdRoute: WorkoutExerciseExerciseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
